name: Laravel Deploy
on:
  pull_request:
    branches: [master]
    types: [closed]
  workflow_dispatch:

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: load repository files
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install

      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate encryption key
        run: php artisan key:generate

      - name: run laravel test
        run: php artisan test

  laravel-deploy:
    needs: [laravel-test]

    runs-on: ubuntu-latest

    steps:
      - name: load repository files
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install

      - name: optimize autoloader
        run: composer install --optimize-autoloader --no-dev

      - name: config cache
        run: php artisan config:cache

      - name: routes cash
        run: php artisan route:cache

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude={'.github/', 'test/', '.env.example', '.gitattributes', '.gitignore', 'artisan', 'composer.json', 'composer.lock', 'package.json', 'phpunit.xml.dist'}
          remote_path: /domains/maxim-dev.ru/public_html/nal-backend/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
