name: Laravel Test
on:
  workflow_dispatch:

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: create folder
        run: mkdir ~/.ssh

      - name: create key
        run: echo '${{ secrets.SSH_KEY }}' > id_rsa

      - name: deploy
        run: rsync -avz ~/text.txt a0761558@141.8.194.74:/home/a0761558/test/
