name: Laravel Test
on:
  workflow_dispatch:

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y

      - name: create file
        run: touch ~/text.txt

      - name: deploy
        run: rsync -avze ~/text.txt a0761558@141.8.194.74:/home/a0761558/test/
