name: Laravel Test
on:
  workflow_dispatch:

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Generate auth hosts
        run: ssh-keyscan -H 141.8.194.74 >> ~/.ssh/known_hosts

      - name: Generate cache
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
          "cd domains/maxim-dev.ru/public_html/nal-backend;
          /usr/local/bin/php81 artisan config:cache;
          /usr/local/bin/php81 artisan route:cache;
          /usr/local/bin/php81 artisan view:cache;
          exit;"
